version: '3.8'

services:
  redis:
    image: redis:7
    container_name: emms-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: emms-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://maglev.proxy.rlwy.net:52003/railway?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: xtmMiBQjZjIyzTZkuFPophHVFujjZtmT
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SECURITY_JWT_TOKEN_SECRET_KEY: abcdefghijklmnopqrstuvwxyz123456
      SECURITY_JWT_TOKEN_EXPIRE_LENGTH: 3600000
      SECURITY_JWT_TOKEN_REFRESH_EXPIRE_LENGTH: 604800000

volumes:
  postgres_data: