package com.emms.backend.entity.enums;

public enum PermissionEntity {

    DASHBOARD_VIEW,

    ASSET_VIEW,
    ASSET_CREATE,
    ASSET_UPDATE,
    ASSET_DELETE,
    ASSET_ASSIGN,

    WORK_ORDER_VIEW,
    WORK_ORDER_CREATE,
    WORK_ORDER_UPDATE,
    WORK_ORDER_DELETE,
    WORK_ORDER_ASSIGN,
    WORK_ORDER_START,
    WORK_ORDER_PAUSE,
    WORK_ORDER_RESUME,
    WORK_ORDER_COMPLETE,
    WORK_ORDER_APPROVE,
    WORK_ORDER_REJECT,

    MAINTENANCE_PLAN_VIEW,
    MAINTENANCE_PLAN_CREATE,
    MAINTENANCE_PLAN_UPDATE,
    MAINTENANCE_PLAN_DELETE,
    MAINTENANCE_PLAN_GENERATE_WO,

    PART_VIEW,
    PART_CREATE,
    PART_UPDATE,
    PART_DELETE,
    PART_USE,
    PART_STOCK_ADJUST,

    NOTIFICATION_VIEW,
    NOTIFICATION_CREATE,
    NOTIFICATION_SEND,
    NOTIFICATION_BROADCAST,

    AUDIT_LOG_VIEW,

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    ROLE_VIEW,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    FILE_VIEW,
    FILE_UPLOAD,
    FILE_DELETE,

    CHAT_VIEW,
    CHAT_SEND,

    REPORT_VIEW,
    REPORT_EXPORT,

    SETTINGS,
    LOCATION_VIEW,
    
    
    LOCATION_CREATE,
    LOCATION_UPDATE,
    LOCATION_DELETE,
    
    METER_VIEW,
    METER_CREATE,
    METER_UPDATE,
    METER_DELETE,
}