package com.emms.backend.entity.enums;

public enum WFMainCondition {


    WORK_ORDER_CREATED,
    WORK_ORDER_UPDATED,
    WORK_ORDER_DELETED,

    WORK_ORDER_STATUS_CHANGED,
    WORK_ORDER_COMPLETED,
    WORK_ORDER_APPROVED,
    WORK_ORDER_REJECTED,

    WORK_ORDER_OVERDUE,
    WORK_ORDER_DUE_SOON,


    PM_TRIGGERED,

    PART_LOW_STOCK,

    MANUAL_TRIGGER
}